interface NavLink {
  label: string;
  path: string;
}

interface Paper {
  id: string,
  name: string;
  brand: string;
  line: string;
  weight: Number;
  type: any;
  finish: string;
  variants: Array<Object>;
}

export const navLinks: NavLink[] = [
  {
    label: "Shop",
    path: "/shop"
  },
  {
    label: "Catalog",
    path: "/catalog",
  },
  {
    label: "Artists",
    path: "/artists",
  },
  {
    label: "About",
    path: "/about",
  },
  {
    label: "Printing",
    path: "/printing",
  },
];

export const printNavLinks: NavLink[] = [
  {
    label: "Printing with Issue Press",
    path: "/printing"
  },
  {
    label: "Intro to Stencil Printing",
    path: "/printing/intro-to-riso"
  },
  {
    label: "Ink Colors",
    path: "/printing/colors"
  },
  {
    label: "Paper",
    path: "/printing/paper"
  },
  {
    label: "File Prep",
    path: "/printing/file-prep"
  },
  {
    label: "Request a Quote",
    path: "/printing/request-quote"
  },
];


export const PaperList: Paper[] = [
  {
    id: "80c_cougar",
    name: "80#c Domtar Cougar Smooth",
    brand: "Domtar",
    line: "Cougar",
    weight: 80,
    type: "cover",
    finish: "smooth",
    variants: [
        {
          id: "80c_domtar_smooth_natural",
          name: "Natural",
          longName: "80#c Domtar Cougar Smooth Natural",
          rgb: "247, 241, 225",
          postLabel: "$",
        },
        {
          id: "80c_domtar_smooth_white",
          name: "White",
          longName: "80#c Domtar Cougar Smooth White",
          rgb: "250,250,250",
          postLabel: "$",
        }
    ]
  },
  {
    id: "70t_cougar",
    name: "70#t Domtar Cougar Smooth",
    brand: "Domtar",
    line: "Cougar",
    weight: 70,
    type: "text",
    finish: "smooth",
    variants: [
        {
          id: "70t_cougar_smooth_natural",
          name: "Natural",
          longName: "70#t Domtar Cougar Smooth Natural",
          rgb: "247, 241, 225",
          postLabel: "$",
        },
        {
          id: "70t_cougar_smooth_white",
          name: "White",
          longName: "70#t Domtar Cougar Smooth White",
          rgb: "250,250,250",
          postLabel: "$",
        }
    ]
  },
  {
    id: "70t_cougar",
    name: "70#t Domtar Cougar Vellum",
    brand: "Domtar",
    line: "Cougar",
    weight: 70,
    type: "text",
    finish: "vellum",
    variants: [
      {
        id: "70t_cougar_vellum_natural",
        name: "Natural",
        longName: "70#t Domtar Cougar Vellum Natural",
        rgb: "247, 241, 225",
        postLabel: "$",
      },
      {
        id: "70t_cougar_vellum_white",
        name: "White",
        longName: "70#t Domtar Cougar Vellum White",
        rgb: "250,250,250",
        postLabel: "$",
      }
  ]
  },
  {
  id: "70t_lettermark_rgbs",
  name: "70#t Domtar LetterMark Colors Opaque Vellum",
  brand: "Domtar",
  line: "LetterMark",
  weight: 80,
  type: "text",
  finish: "vellum",
  variants: [
      {
        id: "70t_lettermark_rgbs_blue",
        name: "Blue",
        longName: "70#t Domtar LetterMark Colors Opaque Blue",
        rgb: "129, 217, 216",
        postLabel: "$",
      },
      {
        id: "70t_lettermark_rgbs_canary",
        name: "Canary",
        longName: "70#t Domtar LetterMark Colors Opaque Canary",
        rgb: "252, 241, 161",
        postLabel: "$",
      },
      {
        id: "70t_lettermark_rgbs_cream",
        name: "Cream",
        longName: "70#t Domtar LetterMark Colors Opaque Cream",
        rgb: "255, 239, 206",
        postLabel: "$",
      },
      {
        id: "70t_lettermark_rgbs_gray",
        name: "Gray",
        longName: "70#t Domtar LetterMark Colors Opaque Gray",
        rgb: "229, 232, 223",
        postLabel: "$",
      },
      {
        id: "70t_lettermark_rgbs_goldenrod",
        name: "Goldenrod",
        longName: "70#t Domtar LetterMark Colors Opaque Goldenrod",
        rgb: "255, 217, 103",
        postLabel: "$",
      },
      {
        id: "70t_lettermark_rgbs_green",
        name: "Green",
        longName: "70#t Domtar LetterMark Colors Opaque Green",
        rgb: "157, 218, 176",
        postLabel: "$",
      },
      {
        id: "70t_lettermark_rgbs_ivory",
        name: "Ivory",
        longName: "70#t Domtar LetterMark Colors Opaque Ivory",
        rgb: "255, 232, 201",
        postLabel: "$",
      },
      {
        id: "70t_lettermark_rgbs_pink",
        name: "Pink",
        longName: "70#t Domtar LetterMark Colors Opaque Pink",
        rgb: "255, 200, 204",
        postLabel: "$",
      },
      {
        id: "70t_lettermark_rgbs_salmon",
        name: "Salmon",
        longName: "70#t Domtar LetterMark Colors Opaque Salmon",
        rgb: "255, 171, 141",
        postLabel: "$",
      },
    ]
  },
  {
    id: "67c_lettermark_vellum_bristol",
    name: "67#c Domtar LetterMark Vellum Bristol",
    brand: "Domtar",
    line: "LetterMark",
    weight: 80,
    type: "cover",
    finish: "vellum",
    variants: [      
      {
        id: "67c_lettermark_vellum_bristol_blue",
        name: "Blue",
        longName: "67#c Domtar LetterMark Vellum Bristol Blue",
        rgb: "129, 217, 216",
        postLabel: "$",
      },
      {
        id: "67c_lettermark_vellum_bristol_britewhite",
        name: "BriteWhite",
        longName: "67#c Domtar LetterMark Vellum Bristol Britewhite",
        rgb: "250,250,250",
        postLabel: "$",
      },  
      {
        id: "67c_lettermark_vellum_bristol_canary",
        name: "Canary",
        longName: "67#c Domtar LetterMark Vellum Bristol Canary",
        rgb: "252, 241, 161",
        postLabel: "$",
      },
      {
        id: "67c_lettermark_vellum_bristol_cream",
        name: "Cream",
        longName: "67#c Domtar LetterMark Vellum Bristol Cream",
        rgb: "255, 239, 206",
        postLabel: "$",
      },
      {
        id: "67c_lettermark_vellum_bristol_goldenrod",
        name: "Goldenrod",
        longName: "67#c Domtar LetterMark Vellum Bristol Goldenrod",
        rgb: "255, 217, 103",
        postLabel: "$",
      },
      {
        id: "67c_lettermark_vellum_bristol_green",
        name: "Green",
        longName: "67#c Domtar LetterMark Vellum Bristol Green",
        rgb: "157, 218, 176",
        postLabel: "$",
      },
      {
        id: "67c_lettermark_vellum_bristol_gray",
        name: "Gray",
        longName: "67#c Domtar LetterMark Vellum Bristol Gray",
        rgb: "229, 232, 223",
        postLabel: "$",
      },
      {
        id: "67c_lettermark_vellum_bristol_ivory",
        name: "Ivory",
        longName: "67#c Domtar LetterMark Vellum Bristol Ivory",
        rgb: "255, 232, 201",
        postLabel: "$",
      },
      {
        id: "67c_lettermark_vellum_bristol_Pink",
        name: "Pink",
        longName: "67#c Domtar LetterMark Vellum Bristol Pink",
        rgb: "255, 200, 204",
        postLabel: "$",
      },
    ]
  },
  {
    id: "60t_astrobrights",
    name: "60#t Neenah Astrobrights Smooth",
    brand: "Neenah",
    line: "Astrobrights",
    weight: 60,
    type: "text",
    finish: "smooth",
    variants: [
      {
        id: "60t_astrobrights_blast-off_blue",
        name: "Blast-off Blue",
        longName: "60#t Neenah Astrobrights Blast-off Blue",
        rgb: "76, 100, 148",
        postLabel: "$$",
      },
      {
        id: "60t_astrobrights_celestial_blue",
        name: "Celestial Blue",
        longName: "60#t Neenah Astrobrights Celestial Blue",
        rgb: "55, 151, 175",
        postLabel: "$$",
      },
      {
        id: "60t_astrobrights_cosmic_orange",
        name: "Cosmic Orange",
        longName: "60#t Neenah Astrobrights Cosmic Orange",
        rgb: "255, 124, 33",
        postLabel: "$$",
      },
      {
        id: "60t_astrobrights_eclipse_black",
        name: "Eclipse Black",
        longName: "60#t Neenah Astrobrights Eclipse Black",
        rgb: "5, 5, 5",
        postLabel: "$$",
      },
      {
        id: "60t_astrobrights_fireball_fuchsia",
        name: "Fireball Fuchsia",
        longName: "60#t Neenah Astrobrights Fireball Fuchsia",
        rgb: "255, 60, 164",
        postLabel: "$$",
      },
      {
        id: "60t_astrobrights_galaxy_gold",
        name: "Galaxy Gold",
        longName: "60#t Neenah Astrobrights Galaxy Gold",
        rgb: "255, 183, 28",
        postLabel: "$$",
      },
      {
        id: "60t_astrobrights_gamma_green",
        name: "Gamma Green",
        longName: "60#t Neenah Astrobrights Gamma Green",
        rgb: "61, 158, 87",
        postLabel: "$$",
      },
      {
        id: "60t_astrobrights_gravity_grape",
        name: "Gravity Grape",
        longName: "60#t Neenah Astrobrights Gravity Grape",
        rgb: "142, 87, 170",
        postLabel: "$$",
      },
      {
        id: "60t_astrobrights_lift-off_lemon",
        name: "Lift-off Lemon",
        longName: "60#t Neenah Astrobrights Lift-off Lemon",
        rgb: "255, 249, 60",
        postLabel: "$$",
      },
      {
        id: "60t_astrobrights_lunar_blue",
        name: "Lunar Blue",
        longName: "60#t Neenah Astrobrights Lunar Blue",
        rgb: "100, 187, 178",
        postLabel: "$$",
      },
      {
        id: "60t_astrobrights_martian_green",
        name: "Martian Green",
        longName: "60#t Neenah Astrobrights Martian Green",
        rgb: "151, 234, 78",
        postLabel: "$$",
      }, 
      {
        id: "60t_astrobrights_orbit_orange",
        name: "Orbit Orange",
        longName: "60#t Neenah Astrobrights Orbit Orange",
        rgb: "253, 102, 52",
        postLabel: "$$",
      },
      {
        id: "60t_astrobrights_outrageous_orchid",
        name: "Outrageous Orchid",
        longName: "60#t Neenah Astrobrights Outrageous Orchid",
        rgb: "227, 99, 174",
        postLabel: "$$",
      },
      {
        id: "60t_astrobrights_planetary_purple",
        name: "Planetary Purple",
        longName: "60#t Neenah Astrobrights Planetary Purple",
        rgb: "190, 106, 158",
        postLabel: "$$",
      },
      {
        id: "60t_astrobrights_plasma_pink",
        name: "Plasma Pink",
        longName: "60#t Neenah Astrobrights Plasma Pink",
        rgb: "255, 86, 125",
        postLabel: "$$",
      },        
      {
        id: "60t_astrobrights_pulsar_pink",
        name: "Pulsar Pink",
        longName: "60#t Neenah Astrobrights Pulsar Pink",
        rgb: "255, 122, 151",
        postLabel: "$$",
      },
      {
        id: "60t_astrobrights_re-entry_red",
        name: "Re-entry Red",
        longName: "60#t Neenah Astrobrights Re-entry Red",
        rgb: "240, 39, 56",
        postLabel: "$$",
      },
      {
        id: "60t_astrobrights_rocket_red",
        name: "Rocket Red",
        longName: "60#t Neenah Astrobrights Rocket Red",
        rgb: "255, 94, 99",
        postLabel: "$$",
      },
      {
        id: "80c_astrobrights_solar_yellow",
        name: "Solar Yellow",
        longName: "80#c Neenah Astrobrights Solar Yellow",
        rgb: "254, 207, 0",
        postLabel: "$$",
      },     
      {
        id: "60t_astrobrights_stardust_white",
        name: "Stardust White",
        longName: "60#t Neenah Astrobrights Stardust White",
        rgb: "255, 240, 211",
        postLabel: "$$",
      },
      {
        id: "60t_astrobrights_sunburst_yellow",
        name: "Sunburst Yellow",
        longName: "60#t Neenah Astrobrights Sunburst Yellow",
        rgb: "254, 207, 0",
        postLabel: "$$",
      },
      {
        id: "60t_astrobrights_terra_green",
        name: "Terra Green",
        longName: "60#t Neenah Astrobrights Terra Green",
        rgb: "189, 216, 51",
        postLabel: "$$",
      },
      {
        id: "60t_astrobrights_terrestrial_teal",
        name: "Terrestrial Teal",
        longName: "60#t Neenah Astrobrights Terrestrial Teal",
        rgb: "40, 168, 155",
        postLabel: "$$",
      },
      {
        id: "60t_astrobrights_venus_violet",
        name: "Venus Violet",
        longName: "60#t Neenah Astrobrights Venus Violet",
        rgb: "134, 123, 199",
        postLabel: "$$",
      },
      {
        id: "60t_astrobrights_vulcan_green",
        name: "Vulcan Green",
        longName: "60#t Neenah Astrobrights Vulcan Green",
        rgb: "188, 232, 67",
        postLabel: "$$",
      },                          
    ]
  },
  {
    id: "65c_astrobrights",
    name: "65#c Neenah Astrobrights Smooth",
    brand: "Neenah",
    line: "Astrobrights",
    weight: 65,
    type: "cover",
    finish: "smooth",
    variants: [
      {
        id: "65c_astrobrights_blast-off_blue",
        name: "Blast-off Blue",
        longName: "65#c Neenah Astrobrights Blast-off Blue",
        rgb: "76, 100, 148",
        postLabel: "$$",
      },
      {
        id: "65c_astrobrights_celestial_blue",
        name: "Celestial Blue",
        longName: "65#c Neenah Astrobrights Celestial Blue",
        rgb: "55, 151, 175",
        postLabel: "$$",
      },
      {
        id: "65c_astrobrights_cosmic_orange",
        name: "Cosmic Orange",
        longName: "65#c Neenah Astrobrights Cosmic Orange",
        rgb: "255, 124, 33",
        postLabel: "$$",
      },
      {
        id: "65c_astrobrights_eclipse_black",
        name: "Eclipse Black",
        longName: "65#c Neenah Astrobrights Eclipse Black",
        rgb: "5, 5, 5",
        postLabel: "$$",
      },
      {
        id: "65c_astrobrights_fireball_fuchsia",
        name: "Fireball Fuchsia",
        longName: "65#c Neenah Astrobrights Fireball Fuchsia",
        rgb: "255, 60, 164",
        postLabel: "$$",
      },
      {
        id: "65c_astrobrights_galaxy_gold",
        name: "Galaxy Gold",
        longName: "65#c Neenah Astrobrights Galaxy Gold",
        rgb: "255, 183, 28",
        postLabel: "$$",
      },
      {
        id: "65c_astrobrights_gamma_green",
        name: "Gamma Green",
        longName: "65#c Neenah Astrobrights Gamma Green",
        rgb: "61, 158, 87",
        postLabel: "$$",
      },
      {
        id: "65c_astrobrights_gravity_grape",
        name: "Gravity Grape",
        longName: "65#c Neenah Astrobrights Gravity Grape",
        rgb: "142, 87, 170",
        postLabel: "$$",
      },
      {
        id: "65c_astrobrights_lift-off_lemon",
        name: "Lift-off Lemon",
        longName: "65#c Neenah Astrobrights Lift-off Lemon",
        rgb: "255, 249, 60",
        postLabel: "$$",
      },
      {
        id: "65c_astrobrights_lunar_blue",
        name: "Lunar Blue",
        longName: "65#c Neenah Astrobrights Lunar Blue",
        rgb: "100, 187, 178",
        postLabel: "$$",
      },
      {
        id: "65c_astrobrights_martian_green",
        name: "Martian Green",
        longName: "65#c Neenah Astrobrights Martian Green",
        rgb: "151, 234, 78",
        postLabel: "$$",
      }, 
      {
        id: "65c_astrobrights_orbit_orange",
        name: "Orbit Orange",
        longName: "65#c Neenah Astrobrights Orbit Orange",
        rgb: "253, 102, 52",
        postLabel: "$$",
      },
      {
        id: "65c_astrobrights_outrageous_orchid",
        name: "Outrageous Orchid",
        longName: "65#c Neenah Astrobrights Outrageous Orchid",
        rgb: "227, 99, 174",
        postLabel: "$$",
      },
      {
        id: "65c_astrobrights_planetary_purple",
        name: "Planetary Purple",
        longName: "65#c Neenah Astrobrights Planetary Purple",
        rgb: "190, 106, 158",
        postLabel: "$$",
      },
      {
        id: "65c_astrobrights_plasma_pink",
        name: "Plasma Pink",
        longName: "65#c Neenah Astrobrights Plasma Pink",
        rgb: "255, 86, 125",
        postLabel: "$$",
      },        
      {
        id: "65c_astrobrights_pulsar_pink",
        name: "Pulsar Pink",
        longName: "65#c Neenah Astrobrights Pulsar Pink",
        rgb: "255, 122, 151",
        postLabel: "$$",
      },
      {
        id: "65c_astrobrights_re-entry_red",
        name: "Re-entry Red",
        longName: "65#c Neenah Astrobrights Re-entry Red",
        rgb: "240, 39, 56",
        postLabel: "$$",
      },
      {
        id: "65c_astrobrights_rocket_red",
        name: "Rocket Red",
        longName: "65#c Neenah Astrobrights Rocket Red",
        rgb: "255, 94, 99",
        postLabel: "$$",
      },
      {
        id: "80c_astrobrights_solar_yellow",
        name: "Solar Yellow",
        longName: "80#c Neenah Astrobrights Solar Yellow",
        rgb: "254, 207, 0",
        postLabel: "$$",
      },     
      {
        id: "65c_astrobrights_stardust_white",
        name: "Stardust White",
        longName: "65#c Neenah Astrobrights Stardust White",
        rgb: "255, 240, 211",
        postLabel: "$$",
      },
      {
        id: "65c_astrobrights_sunburst_yellow",
        name: "Sunburst Yellow",
        longName: "65#c Neenah Astrobrights Sunburst Yellow",
        rgb: "254, 207, 0",
        postLabel: "$$",
      },
      {
        id: "65c_astrobrights_terra_green",
        name: "Terra Green",
        longName: "65#c Neenah Astrobrights Terra Green",
        rgb: "189, 216, 51",
        postLabel: "$$",
      },
      {
        id: "65c_astrobrights_terrestrial_teal",
        name: "Terrestrial Teal",
        longName: "65#c Neenah Astrobrights Terrestrial Teal",
        rgb: "40, 168, 155",
        postLabel: "$$",
      },
      {
        id: "65c_astrobrights_venus_violet",
        name: "Venus Violet",
        longName: "65#c Neenah Astrobrights Venus Violet",
        rgb: "134, 123, 199",
        postLabel: "$$",
      },
      {
        id: "65c_astrobrights_vulcan_green",
        name: "Vulcan Green",
        longName: "65#c Neenah Astrobrights Vulcan Green",
        rgb: "188, 232, 67",
        postLabel: "$$",
      },                          
    ]
  },
  {
    id: "80c_astrobrights",
    name: "80#c Neenah Astrobrights Smooth",
    brand: "Neenah",
    line: "Astrobrights",
    weight: 80,
    type: "cover",
    finish: "smooth",
    variants: [
      {
        id: "80c_astrobrights_cosmic_orange",
        name: "Cosmic Orange",
        longName: "80#c Neenah Astrobrights Cosmic Orange",
        rgb: "255, 124, 33",
        postLabel: "$$",
      },
      {
        id: "80c_astrobrights_eclipse_black",
        name: "Eclipse Black",
        longName: "80#c Neenah Astrobrights Eclipse Black",
        rgb: "5, 5, 5",
        postLabel: "$$",
      },
      {
        id: "80c_astrobrights_lunar_blue",
        name: "Lunar Blue",
        longName: "80#c Neenah Astrobrights Lunar Blue",
        rgb: "100, 187, 178",
        postLabel: "$$",
      },
      {
        id: "80c_astrobrights_re-entry_red",
        name: "Re-entry Red",
        longName: "80#c Neenah Astrobrights Re-entry Red",
        rgb: "240, 39, 56",
        postLabel: "$$",
      },
      {
        id: "80c_astrobrights_solar_yellow",
        name: "Solar Yellow",
        longName: "80#c Neenah Astrobrights Solar Yellow",
        rgb: "254, 207, 0",
        postLabel: "$$",
      },
      {
        id: "80c_astrobrights_terra_green",
        name: "Terra Green",
        longName: "80#c Neenah Astrobrights Terra Green",
        rgb: "189, 216, 51",
        postLabel: "$$",
      },                      
    ]
  },
  {
    id: "70t_french_speckletone",
    name: "70#t French Paper Co. Speckletone Vellum",
    brand: "French Paper Co.",
    line: "Speckletone",
    weight: 70,
    type: "text",
    finish: "vellum",
    variants: [
      {
        id: "70t_french_speckletone_black",
        name: "Black",
        longName: "70#t French Paper Co. Speckletone Black",
        rgb: "41, 37, 38",
        postLabel: "$$$",
      },
      {
        id: "70t_french_speckletone_brown",
        name: "Brown",
        longName: "70#t French Paper Co. Speckletone Brown",
        rgb: "91, 67, 31"
      },
      {
        id: "70t_french_speckletone_chocolate",
        name: "Chocolate",
        longName: "70#t French Paper Co. Speckletone Chocolate",
        rgb: "67, 53, 42",
        postLabel: "$$$",
      },
      {
        id: "70t_french_speckletone_cream",
        name: "Cream",
        longName: "70#t French Paper Co. Speckletone Cream",
        rgb: "235, 221, 192",
        postLabel: "$$$",
      },
      {
        id: "70t_french_speckletone_kraft",
        name: "Kraft",
        longName: "70#t French Paper Co. Speckletone Kraft",
        rgb: "207, 179, 144",
        postLabel: "$$$",
      },
      {
        id: "70t_french_speckletone_madero",
        name: "Madero Beach",
        longName: "70#t French Paper Co. Speckletone Madero Beach",
        rgb: "237, 231, 219",
        postLabel: "$$$",
      },
      {
        id: "70t_french_speckletone_natural",
        name: "Natural",
        longName: "70#t French Paper Co. Speckletone Natural",
        rgb: "205, 190, 171",
        postLabel: "$$$",
      },
      {
        id: "70t_french_speckletone_oatmeal",
        name: "Oatmeal",
        longName: "70#t French Paper Co. Speckletone Oatmeal",
        rgb: "205, 182, 151",
        postLabel: "$$$",
      },
      {
        id: "70t_french_speckletone_old_green",
        name: "Old Green",
        longName: "70#t French Paper Co. Speckletone Old Green",
        rgb: "210, 199, 179",
        postLabel: "$$$",
      },
      {
        id: "70t_french_speckletone_olive",
        name: "Olive",
        longName: "70#t French Paper Co. Speckletone Olive",
        rgb: "89, 80, 51",
        postLabel: "$$$",
      },
      {
        id: "70t_french_speckletone_sand",
        name: "Sand",
        longName: "70#t French Paper Co. Speckletone Sand",
        rgb: "220, 202, 180",
        postLabel: "$$$",
      },
      {
        id: "70t_french_speckletone_starch_mint",
        name: "Starch Mint",
        longName: "70#t French Paper Co. Speckletone Starch Mint",
        rgb: "243, 242, 222",
        postLabel: "$$$",
      },
      {
        id: "70t_french_speckletone_starch_rain",
        name: "Starch Rain",
        longName: "70#t French Paper Co. Speckletone Starch Rain",
        rgb: "227, 239, 239",
        postLabel: "$$$",
      },
      {
        id: "70t_french_speckletone_starch_white",
        name: "Starch White",
        longName: "70#t French Paper Co. Speckletone Starch White",
        rgb: "253, 252, 250",
        postLabel: "$$$",
      },
      {
        id: "70t_french_speckletone_true_white",
        name: "True White",
        longName: "70#t French Paper Co. Speckletone True White",
        rgb: "246, 241, 235",
        postLabel: "$$$",
      },
      {
        id: "70t_french_speckletone_wine",
        name: "Wine",
        longName: "70#t French Paper Co. Speckletone Wine",
        rgb: "77, 41, 41",
        postLabel: "$$$",
      },
    ]
  },
  {
    id: "80c_french_speckletone",
    name: "80#c French Paper Co. Speckletone Vellum",
    brand: "French Paper Co.",
    line: "Speckletone",
    weight: 80,
    type: "cover",
    finish: "vellum",
    variants: [
      {
        id: "80c_french_speckletone_black",
        name: "Black",
        longName: "80#c French Paper Co. Speckletone Black",
        rgb: "41, 37, 38",
        postLabel: "$$$",
      },
      {
        id: "80c_french_speckletone_cream",
        name: "Cream",
        longName: "80#c French Paper Co. Speckletone Cream",
        rgb: "235, 221, 192",
        postLabel: "$$$",
      },
      {
        id: "80c_french_speckletone_kraft",
        name: "Kraft",
        longName: "80#c French Paper Co. Speckletone Kraft",
        rgb: "207, 179, 144",
        postLabel: "$$$",
      },
      {
        id: "80c_french_speckletone_madero",
        name: "Madero Beach",
        longName: "80#c French Paper Co. Speckletone Madero Beach",
        rgb: "237, 231, 219",
        postLabel: "$$$",
      },
      {
        id: "80c_french_speckletone_natural",
        name: "Natural",
        longName: "80#c French Paper Co. Speckletone Natural",
        rgb: "205, 190, 171",
        postLabel: "$$$",
      },
      {
        id: "80c_french_speckletone_oatmeal",
        name: "Oatmeal",
        longName: "80#c French Paper Co. Speckletone Oatmeal",
        rgb: "205, 182, 151",
        postLabel: "$$$",
      },
      {
        id: "80c_french_speckletone_old_green",
        name: "Old Green",
        longName: "80#c French Paper Co. Speckletone Old Green",
        rgb: "210, 199, 179",
        postLabel: "$$$",
      },
      {
        id: "80c_french_speckletone_sand",
        name: "Sand",
        longName: "80#c French Paper Co. Speckletone Sand",
        rgb: "220, 202, 180",
        postLabel: "$$$",
      },
      {
        id: "80c_french_speckletone_starch_rain",
        name: "Starch Rain",
        longName: "80#c French Paper Co. Speckletone Starch Rain",
        rgb: "227, 239, 239",
        postLabel: "$$$",
      },
      {
        id: "80c_french_speckletone_starch_white",
        name: "Starch White",
        longName: "80#c French Paper Co. Speckletone Starch White",
        rgb: "253, 252, 250",
        postLabel: "$$$",
      },
      {
        id: "80c_french_speckletone_true_white",
        name: "True White",
        longName: "80#c French Paper Co. Speckletone True White",
        rgb: "246, 241, 235",
        postLabel: "$$$",
      },
    ]
  },
  {
    id: "70t_french_construction",
    name: "70#t French Paper Co. Construction Vellum",
    brand: "French Paper Co.",
    line: "Construction",
    weight: 70,
    type: "text",
    finish: "vellum",
    variants: [
      {      
        id: "70t_french_construction_blacktop",
        name: "Blacktop",
        longName: "70#t French Paper Co. Construction Blacktop",
        rgb: "37, 37, 37",
        postLabel: "$$$",
      },
      {      
        id: "70t_french_construction_brick_red",
        name: "Brick Red",
        longName: "70#t French Paper Co. Construction Brick Red",
        rgb: "126, 77, 73",
        postLabel: "$$$",
      },
      {      
        id: "70t_french_construction_cement_green",
        name: "Cement Green",
        longName: "70#t French Paper Co. Construction Cement Green",
        rgb: "221, 215, 181",
        postLabel: "$$$",
      },
      {      
        id: "70t_french_construction_charcoal_brown",
        name: "Charcoal Brown",
        longName: "70#t French Paper Co. Construction Charcoal Brown",
        rgb: "89, 82, 76",
        postLabel: "$$$",
      },
      {      
        id: "70t_french_construction_electric_red",
        name: "Electric Red",
        longName: "70#t French Paper Co. Construction Electric Red",
        rgb: "154, 46, 62",
        postLabel: "$$$",
      },
      {      
        id: "70t_french_construction_factory_green",
        name: "Factory Green",
        longName: "70#t French Paper Co. Construction Factory Green",
        rgb: "187, 177, 120",
        postLabel: "$$$",
      },
      {      
        id: "70t_french_construction_fuse_green",
        name: "Fuse Green",
        longName: "70#t French Paper Co. Construction Fuse Green",
        rgb: "213, 171, 55",
        postLabel: "$$$",
      },    
      {      
        id: "70t_french_construction_grout_gray",
        name: "Grout Gray",
        longName: "70#t French Paper Co. Construction Grout Gray",
        rgb: "220, 222, 212",
        postLabel: "$$$",
      },
      {      
        id: "70t_french_construction_insulation_pink",
        name: "Insulation Pink",
        longName: "70#t French Paper Co. Construction Insulation Pink",
        rgb: "250, 239, 233",
        postLabel: "$$$",
      },
      {      
        id: "70t_french_construction_nightshift_blue",
        name: "Nightshift Blue",
        longName: "70#t French Paper Co. Construction Nightshift Blue",
        rgb: "36, 53, 61",
        postLabel: "$$$",
      },   
      {      
        id: "70t_french_construction_paver_red",
        name: "Paver Red",
        longName: "70#t French Paper Co. Construction Paver Red",
        rgb: "95, 49, 52",
        postLabel: "$$$",
      },
      {      
        id: "70t_french_construction_pure_white",
        name: "Pure White",
        longName: "70#t French Paper Co. Construction Pure White",
        rgb: "252, 252, 252",
        postLabel: "$$$",
      },
      {      
        id: "70t_french_construction_recycled_white",
        name: "Recycled White",
        longName: "70#t French Paper Co. Construction Recycled White",
        rgb: "249, 247, 248",
        postLabel: "$$$",
      },  
      {      
        id: "70t_french_construction_steel_blue",
        name: "Steel Blue",
        longName: "70#t French Paper Co. Construction Steel Blue",
        rgb: "145, 156, 152",
        postLabel: "$$$",
      }, 
      {      
        id: "70t_french_construction_tile_green",
        name: "Tile Green",
        longName: "70#t French Paper Co. Construction Tile Green",
        rgb: "235, 237, 224",
        postLabel: "$$$",
      },
      {      
        id: "70t_french_construction_timber_green",
        name: "Timber Green",
        longName: "70#t French Paper Co. Construction Timber Green",
        rgb: "32, 49, 43",
        postLabel: "$$$",
      },
      {      
        id: "70t_french_construction_whitewash",
        name: "Whitewash",
        longName: "70#t French Paper Co. Construction Whitewash",
        rgb: "245, 244, 226",
        postLabel: "$$$",
      },               
    ]
  },
  {
    id: "80c_french_construction",
    name: "80#c French Paper Co. Construction Vellum",
    brand: "French Paper Co.",
    line: "Construction",
    weight: 80,
    type: "cover",
    finish: "vellum",
    variants: [
      {      
        id: "80c_french_construction_blacktop",
        name: "Blacktop",
        longName: "80#c French Paper Co. Construction Blacktop",
        rgb: "37, 37, 37",
        postLabel: "$$$",
      },
      {      
        id: "80c_french_construction_brick_red",
        name: "Brick Red",
        longName: "80#c French Paper Co. Construction Brick Red",
        rgb: "126, 77, 73",
        postLabel: "$$$",
      },
      {      
        id: "80c_french_construction_cement_green",
        name: "Cement Green",
        longName: "80#c French Paper Co. Construction Cement Green",
        rgb: "221, 215, 181",
        postLabel: "$$$",
      },
      {      
        id: "80c_french_construction_charcoal_brown",
        name: "Charcoal Brown",
        longName: "80#c French Paper Co. Construction Charcoal Brown",
        rgb: "89, 82, 76",
        postLabel: "$$$",
      },
      {      
        id: "80c_french_construction_electric_red",
        name: "Electric Red",
        longName: "80#c French Paper Co. Construction Electric Red",
        rgb: "154, 46, 62",
        postLabel: "$$$",
      },
      {      
        id: "80c_french_construction_factory_green",
        name: "Factory Green",
        longName: "80#c French Paper Co. Construction Factory Green",
        rgb: "187, 177, 120",
        postLabel: "$$$",
      },
      {      
        id: "80c_french_construction_fuse_green",
        name: "Fuse Green",
        longName: "80#c French Paper Co. Construction Fuse Green",
        rgb: "213, 171, 55",
        postLabel: "$$$",
      },    
      {      
        id: "80c_french_construction_grout_gray",
        name: "Grout Gray",
        longName: "80#c French Paper Co. Construction Grout Gray",
        rgb: "220, 222, 212",
        postLabel: "$$$",
      },
      {      
        id: "80c_french_construction_insulation_pink",
        name: "Insulation Pink",
        longName: "80#c French Paper Co. Construction Insulation Pink",
        rgb: "250, 239, 233",
        postLabel: "$$$",
      },
      {      
        id: "80c_french_construction_nightshift_blue",
        name: "Nightshift Blue",
        longName: "80#c French Paper Co. Construction Nightshift Blue",
        rgb: "36, 53, 61",
        postLabel: "$$$",
      },   
      {      
        id: "80c_french_construction_paver_red",
        name: "Paver Red",
        longName: "80#c French Paper Co. Construction Paver Red",
        rgb: "95, 49, 52",
        postLabel: "$$$",
      },
      {      
        id: "80c_french_construction_pure_white",
        name: "Pure White",
        longName: "80#c French Paper Co. Construction Pure White",
        rgb: "252, 252, 252",
        postLabel: "$$$",
      },
      {      
        id: "80c_french_construction_recycled_white",
        name: "Recycled White",
        longName: "80#c French Paper Co. Construction Recycled White",
        rgb: "249, 247, 248",
        postLabel: "$$$",
      },  
      {      
        id: "80c_french_construction_steel_blue",
        name: "Steel Blue",
        longName: "80#c French Paper Co. Construction Steel Blue",
        rgb: "145, 156, 152",
        postLabel: "$$$",
      }, 
      {      
        id: "80c_french_construction_tile_green",
        name: "Tile Green",
        longName: "80#c French Paper Co. Construction Tile Green",
        rgb: "235, 237, 224",
        postLabel: "$$$",
      },
      {      
        id: "80c_french_construction_timber_green",
        name: "Timber Green",
        longName: "80#c French Paper Co. Construction Timber Green",
        rgb: "32, 49, 43",
        postLabel: "$$$",
      },
      {      
        id: "80c_french_construction_whitewash",
        name: "Whitewash",
        longName: "80#c French Paper Co. Construction Whitewash",
        rgb: "245, 244, 226",
        postLabel: "$$$",
      },               
    ]
  },
  {
    id: "70t_french_pop-tone",
    name: "70#t French Paper Co. Pop-tone Vellum",
    brand: "French Paper Co.",
    line: "Pop-Tone",
    weight: 70,
    type: "text",
    finish: "vellum",
    variants: [
      {      
        id: "70t_french_pop-tone_banana_split",
        name: "Banana Split",
        longName: "70#t French Paper Co. Pop-tone Banana Split",
        rgb: "245, 223, 115",
        postLabel: "$$$",
      },
      {      
        id: "70t_french_pop-tone_berrylicious",
        name: "Berrylicious",
        longName: "70#t French Paper Co. Pop-tone Berrylicious",
        rgb: "174, 216, 222",
        postLabel: "$$$",
      },
      {      
        id: "70t_french_pop-tone_black_licorice",
        name: "Black Licorice",
        longName: "70#t French Paper Co. Pop-tone Black Licorice",
        rgb: "50, 48, 48",
        postLabel: "$$$",
      },
      {      
        id: "70t_french_pop-tone_blu_raspberry",
        name: "Blu Raspberry",
        longName: "70#t French Paper Co. Pop-tone Blu Raspberry",
        rgb: "126, 208, 214",
        postLabel: "$$$",
      },
      {      
        id: "70t_french_pop-tone_bubblegum",
        name: "Bubblegum",
        longName: "70#t French Paper Co. Pop-tone Bubblegum",
        rgb: "231, 193, 190",
        postLabel: "$$$",
      },
      {      
        id: "70t_french_pop-tone_cotton_candy",
        name: "Cotton Candy",
        longName: "70#t French Paper Co. Pop-tone Cotton Candy",
        rgb: "227, 182, 201",
        postLabel: "$$$",
      },
      {      
        id: "70t_french_pop-tone_grape_jelly",
        name: "Grape Jelly",
        longName: "70#t French Paper Co. Pop-tone Grape Jelly",
        rgb: "162, 142, 198",
        postLabel: "$$$",
      },
      {      
        id: "70t_french_pop-tone_grapesicle",
        name: "Grapesicle",
        longName: "70#t French Paper Co. Pop-tone Grapesicle",
        rgb: "219, 208, 221",
        postLabel: "$$$",
      },
      {      
        id: "70t_french_pop-tone_gumdrop_green",
        name: "Gumdrop Green",
        longName: "70#t French Paper Co. Pop-tone Gumdrop Green",
        rgb: "136, 173, 87",
        postLabel: "$$$",
      },
      {      
        id: "70t_french_pop-tone_hot_fudge",
        name: "Hot Fudge",
        longName: "70#t French Paper Co. Pop-tone Hot Fudge",
        rgb: "79, 59, 50",
        postLabel: "$$$",
      },
      {      
        id: "70t_french_pop-tone_jellybean_green",
        name: "Jellybean Green",
        longName: "70#t French Paper Co. Pop-tone Jellybean Green",
        rgb: "110, 122, 45",
        postLabel: "$$$",
      },
      {      
        id: "70t_french_pop-tone_lemon_drop",
        name: "Lemon Drop",
        longName: "70#t French Paper Co. Pop-tone Lemon Drop",
        rgb: "239, 214, 4",
        postLabel: "$$$",
      },
      {      
        id: "70t_french_pop-tone_limeade",
        name: "Limeade",
        longName: "70#t French Paper Co. Pop-tone Limeade",
        rgb: "184, 215, 166",
        postLabel: "$$$",
      },
      {      
        id: "70t_french_pop-tone_orange_fizz",
        name: "Orange Fizz",
        longName: "70#t French Paper Co. Pop-tone Orange Fizz",
        rgb: "236, 152, 70",
        postLabel: "$$$",
      },
      {      
        id: "70t_french_pop-tone_pink_lemonade",
        name: "Pink Lemonade",
        longName: "70#t French Paper Co. Pop-tone Pink Lemonade",
        rgb: "244, 202, 203",
        postLabel: "$$$",
      },
      {      
        id: "70t_french_pop-tone_razzleberry",
        name: "Razzleberry",
        longName: "70#t French Paper Co. Pop-tone Razzleberry",
        rgb: "239, 78, 141",
        postLabel: "$$$",
      },
      {      
        id: "70t_french_pop-tone_red_hot",
        name: "Red Hot",
        longName: "70#t French Paper Co. Pop-tone Red Hot",
        rgb: "215, 49, 64",
        postLabel: "$$$",
      },
      {      
        id: "70t_french_pop-tone_spearmint",
        name: "Spearmint",
        longName: "70#t French Paper Co. Pop-tone Spearmint",
        rgb: "206, 226, 203",
        postLabel: "$$$",
      },
      {      
        id: "70t_french_pop-tone_sweet_tooth",
        name: "Sweet Tooth",
        longName: "70#t French Paper Co. Pop-tone Sweet Tooth",
        rgb: "234, 234, 234",
        postLabel: "$$$",
      },
      {      
        id: "70t_french_pop-tone_tangy_orange",
        name: "Tangy Orange",
        longName: "70#t French Paper Co. Pop-tone Tangy Orange",
        rgb: "221, 82, 72",
        postLabel: "$$$",
      },
      {      
        id: "70t_french_pop-tone_whip_cream",
        name: "Whip Cream",
        longName: "70#t French Paper Co. Pop-tone Whip Cream",
        rgb: "240, 238, 234",
        postLabel: "$$$",
      },
      {      
        id: "70t_french_pop-tone_wild_cherry",
        name: "Wild Cherry",
        longName: "70#t French Paper Co. Pop-tone Wild Cherry",
        rgb: "194, 28, 53",
        postLabel: "$$$",
      },
    ]
  },
  {
    id: "65c_french_pop-tone",
    name: "65#c French Paper Co. Pop-tone Vellum",
    brand: "French Paper Co.",
    line: "Pop-Tone",
    weight: 65,
    type: "cover",
    finish: "vellum",
    variants: [
      {      
        id: "65c_french_pop-tone_banana_split",
        name: "Banana Split",
        longName: "65#c French Paper Co. Pop-tone Banana Split",
        rgb: "245, 223, 115",
        postLabel: "$$$",
      },
      {      
        id: "65c_french_pop-tone_berrylicious",
        name: "Berrylicious",
        longName: "65#c French Paper Co. Pop-tone Berrylicious",
        rgb: "174, 216, 222",
        postLabel: "$$$",
      },
      {      
        id: "65c_french_pop-tone_black_licorice",
        name: "Black Licorice",
        longName: "65#c French Paper Co. Pop-tone Black Licorice",
        rgb: "50, 48, 48",
        postLabel: "$$$",
      },
      {      
        id: "65c_french_pop-tone_blu_raspberry",
        name: "Blu Raspberry",
        longName: "65#c French Paper Co. Pop-tone Blu Raspberry",
        rgb: "126, 208, 214",
        postLabel: "$$$",
      },
      {      
        id: "65c_french_pop-tone_bubblegum",
        name: "Bubblegum",
        longName: "65#c French Paper Co. Pop-tone Bubblegum",
        rgb: "231, 193, 190",
        postLabel: "$$$",
      },
      {      
        id: "65c_french_pop-tone_cotton_candy",
        name: "Cotton Candy",
        longName: "65#c French Paper Co. Pop-tone Cotton Candy",
        rgb: "227, 182, 201",
        postLabel: "$$$",
      },
      {      
        id: "65c_french_pop-tone_grape_jelly",
        name: "Grape Jelly",
        longName: "65#c French Paper Co. Pop-tone Grape Jelly",
        rgb: "162, 142, 198",
        postLabel: "$$$",
      },
      {      
        id: "65c_french_pop-tone_grapesicle",
        name: "Grapesicle",
        longName: "65#c French Paper Co. Pop-tone Grapesicle",
        rgb: "219, 208, 221",
        postLabel: "$$$",
      },
      {      
        id: "65c_french_pop-tone_gumdrop_green",
        name: "Gumdrop Green",
        longName: "65#c French Paper Co. Pop-tone Gumdrop Green",
        rgb: "136, 173, 87",
        postLabel: "$$$",
      },
      {      
        id: "65c_french_pop-tone_hot_fudge",
        name: "Hot Fudge",
        longName: "65#c French Paper Co. Pop-tone Hot Fudge",
        rgb: "79, 59, 50",
        postLabel: "$$$",
      },
      {      
        id: "65c_french_pop-tone_jellybean_green",
        name: "Jellybean Green",
        longName: "65#c French Paper Co. Pop-tone Jellybean Green",
        rgb: "110, 122, 45",
        postLabel: "$$$",
      },
      {      
        id: "65c_french_pop-tone_lemon_drop",
        name: "Lemon Drop",
        longName: "65#c French Paper Co. Pop-tone Lemon Drop",
        rgb: "239, 214, 4",
        postLabel: "$$$",
      },
      {      
        id: "65c_french_pop-tone_limeade",
        name: "Limeade",
        longName: "65#c French Paper Co. Pop-tone Limeade",
        rgb: "184, 215, 166",
        postLabel: "$$$",
      },
      {      
        id: "65c_french_pop-tone_orange_fizz",
        name: "Orange Fizz",
        longName: "65#c French Paper Co. Pop-tone Orange Fizz",
        rgb: "236, 152, 70",
        postLabel: "$$$",
      },
      {      
        id: "65c_french_pop-tone_pink_lemonade",
        name: "Pink Lemonade",
        longName: "65#c French Paper Co. Pop-tone Pink Lemonade",
        rgb: "244, 202, 203",
        postLabel: "$$$",
      },
      {      
        id: "65c_french_pop-tone_razzleberry",
        name: "Razzleberry",
        longName: "65#c French Paper Co. Pop-tone Razzleberry",
        rgb: "239, 78, 141",
        postLabel: "$$$",
      },
      {      
        id: "65c_french_pop-tone_red_hot",
        name: "Red Hot",
        longName: "65#c French Paper Co. Pop-tone Red Hot",
        rgb: "215, 49, 64",
        postLabel: "$$$",
      },
      {      
        id: "65c_french_pop-tone_spearmint",
        name: "Spearmint",
        longName: "65#c French Paper Co. Pop-tone Spearmint",
        rgb: "206, 226, 203",
        postLabel: "$$$",
      },
      {      
        id: "65c_french_pop-tone_sweet_tooth",
        name: "Sweet Tooth",
        longName: "65#c French Paper Co. Pop-tone Sweet Tooth",
        rgb: "234, 234, 234",
        postLabel: "$$$",
      },
      {      
        id: "65c_french_pop-tone_tangy_orange",
        name: "Tangy Orange",
        longName: "65#c French Paper Co. Pop-tone Tangy Orange",
        rgb: "221, 82, 72",
        postLabel: "$$$",
      },
      {      
        id: "65c_french_pop-tone_whip_cream",
        name: "Whip Cream",
        longName: "65#c French Paper Co. Pop-tone Whip Cream",
        rgb: "240, 238, 234",
        postLabel: "$$$",
      },
      {      
        id: "65c_french_pop-tone_wild_cherry",
        name: "Wild Cherry",
        longName: "65#c French Paper Co. Pop-tone Wild Cherry",
        rgb: "194, 28, 53",
        postLabel: "$$$",
      },
    ]
  },
  {
    id: "60t_french_glo-tone",
    name: "60#t French Paper Co. Glo-tone Vellum",
    brand: "French Paper Co.",
    line: "Glo-Tone",
    weight: 60,
    type: "text",
    finish: "vellum",
    variants: [
      {      
        id: "60t_french_glo-tone_blue_light",
        name: "Blue Light",
        longName: "60#t French Paper Co. Glo-tone Blue Light",
        rgb: "39, 174, 199",
        postLabel: "$$$",
      },
      {      
        id: "60t_french_glo-tone_green_light",
        name: "Green Light",
        longName: "60#t French Paper Co. Glo-tone Green Light",
        rgb: "46, 137, 92",
        postLabel: "$$$",
      },
      {      
        id: "60t_french_glo-tone_neon_orange",
        name: "Neon Orange",
        longName: "60#t French Paper Co. Glo-tone Neon Orange",
        rgb: "253, 151, 64",
        postLabel: "$$$",
      },
      {      
        id: "60t_french_glo-tone_neon_yellow",
        name: "Neon Yellow",
        longName: "60#t French Paper Co. Glo-tone Neon Yellow",
        rgb: "208, 228, 96",
        postLabel: "$$$",
      },
      {      
        id: "60t_french_glo-tone_orange_light",
        name: "Orange Light",
        longName: "60#t French Paper Co. Glo-tone Orange Light",
        rgb: "227, 88, 50",
        postLabel: "$$$",
      },
      {      
        id: "60t_french_glo-tone_purple_light",
        name: "Purple Light",
        longName: "60#t French Paper Co. Glo-tone Purple Light",
        rgb: "221, 141, 198",
        postLabel: "$$$",
      },
      {      
        id: "60t_french_glo-tone_red_light",
        name: "Red Light",
        longName: "60#t French Paper Co. Glo-tone Red Light",
        rgb: "200, 42, 58",
        postLabel: "$$$",
      },  
      {      
        id: "60t_french_glo-tone_shocking_green",
        name: "Shocking Green",
        longName: "60#t French Paper Co. Glo-tone Shocking Green",
        rgb: "206, 251, 88",
        postLabel: "$$$",
      },
      {      
        id: "60t_french_glo-tone_shocking_pink",
        name: "Shocking Green",
        longName: "60#t French Paper Co. Glo-tone Shocking Pink",
        rgb: "255, 144, 166",
        postLabel: "$$$",
      },  
      {      
        id: "60t_french_glo-tone_shocking_yellow",
        name: "Shocking Yellow",
        longName: "60#t French Paper Co. Glo-tone Shocking Yellow",
        rgb: "254, 197, 24",
        postLabel: "$$$",
      },         
      {      
        id: "60t_french_glo-tone_sun_light",
        name: "Sun Light",
        longName: "60#t French Paper Co. Glo-tone Sun Light",
        rgb: "225, 189, 7",
        postLabel: "$$$",
      }, 
      {      
        id: "60t_french_glo-tone_yellow_light",
        name: "Yellow Light",
        longName: "60#t French Paper Co. Glo-tone Yellow Light",
        rgb: "234, 195, 56",
        postLabel: "$$$",
      },    
    ]
  },
  {
    id: "65c_french_pop-tone",
    name: "65#c French Paper Co. Glo-tone Vellum",
    brand: "French Paper Co.",
    line: "Glo-Tone",
    weight: 60,
    type: "cover",
    finish: "vellum",
    variants: [
      {      
        id: "65c_french_glo-tone_blue_light",
        name: "Blue Light",
        longName: "65#c French Paper Co. Glo-tone Blue Light",
        rgb: "39, 174, 199",
        postLabel: "$$$",
      },
      {      
        id: "65c_french_glo-tone_green_light",
        name: "Green Light",
        longName: "65#c French Paper Co. Glo-tone Green Light",
        rgb: "46, 137, 92",
        postLabel: "$$$",
      },
      {      
        id: "65c_french_glo-tone_neon_orange",
        name: "Neon Orange",
        longName: "65#c French Paper Co. Glo-tone Neon Orange",
        rgb: "253, 151, 64",
        postLabel: "$$$",
      },
      {      
        id: "65c_french_glo-tone_neon_yellow",
        name: "Neon Yellow",
        longName: "65#c French Paper Co. Glo-tone Neon Yellow",
        rgb: "208, 228, 96",
        postLabel: "$$$",
      },
      {      
        id: "65c_french_glo-tone_orange_light",
        name: "Orange Light",
        longName: "65#c French Paper Co. Glo-tone Orange Light",
        rgb: "227, 88, 50",
        postLabel: "$$$",
      },
      {      
        id: "65c_french_glo-tone_purple_light",
        name: "Purple Light",
        longName: "65#c French Paper Co. Glo-tone Purple Light",
        rgb: "221, 141, 198",
        postLabel: "$$$",
      },
      {      
        id: "65c_french_glo-tone_red_light",
        name: "Red Light",
        longName: "65#c French Paper Co. Glo-tone Red Light",
        rgb: "200, 42, 58",
        postLabel: "$$$",
      },  
      {      
        id: "65c_french_glo-tone_shocking_green",
        name: "Shocking Green",
        longName: "65#c French Paper Co. Glo-tone Shocking Green",
        rgb: "206, 251, 88",
        postLabel: "$$$",
      },
      {      
        id: "65c_french_glo-tone_shocking_pink",
        name: "Shocking Green",
        longName: "65#c French Paper Co. Glo-tone Shocking Pink",
        rgb: "255, 144, 166",
        postLabel: "$$$",
      },  
      {      
        id: "65c_french_glo-tone_shocking_yellow",
        name: "Shocking Yellow",
        longName: "65#c French Paper Co. Glo-tone Shocking Yellow",
        rgb: "254, 197, 24",
        postLabel: "$$$",
      },         
      {      
        id: "65c_french_glo-tone_sun_light",
        name: "Sun Light",
        longName: "65#c French Paper Co. Glo-tone Sun Light",
        rgb: "225, 189, 7",
        postLabel: "$$$",
      }, 
      {      
        id: "65c_french_glo-tone_yellow_light",
        name: "Yellow Light",
        longName: "65#c French Paper Co. Glo-tone Yellow Light",
        rgb: "234, 195, 56",
        postLabel: "$$$",
      },    
    ]
  },
  {
    id: "70t_french_dur-o-tone",
    name: "70#t French Paper Co. Dur-O-Tone Vellum",
    brand: "French Paper Co.",
    line: "Dur-O-Tone",
    weight: 70,
    type: "text",
    finish: "vellum",
    variants: [
      {      
        id: "70t_french_dur-o-tone_aged_newsprint",
        name: "Aged Newsprint",
        longName: "70#t French Paper Co. Dur-O-Tone Aged Newsprint",
        rgb: "223, 208, 188",
        postLabel: "$$$",
      },
      {      
        id: "70t_french_dur-o-tone_newsprint_extra_white",
        name: "Newsprint Extra White",
        longName: "70#t French Paper Co. Dur-O-Tone Newsprint Extra White",
        rgb: "231, 230, 226",
        postLabel: "$$$",
      },
      {      
        id: "70t_french_dur-o-tone_newsprint_white",
        name: "Newsprint White",
        longName: "70#t French Paper Co. Dur-O-Tone Newsprint White",
        rgb: "229, 219, 205",
        postLabel: "$$$",
      },
      {      
        id: "70t_french_dur-o-tone_packing_brown_wrap",
        name: "Packing Brown Wrap",
        longName: "70#t French Paper Co. Dur-O-Tone Packing Brown Wrap",
        rgb: "190, 148, 84",
        postLabel: "$$$",
      },
      {
        id: "70t_french_dur-o-tone_steel_grey",
        name: "Steel Grey",
        longName: "70#t French Paper Co. Dur-O-Tone Steel Grey",
        rgb: "85, 84, 84",
        postLabel: "$$$",
      },
    ]
  },
  {
    id: "80c_french_dur-o-tone",
    name: "80#c French Paper Co. Dur-O-Tone Vellum",
    brand: "French Paper Co.",
    line: "Dur-O-Tone",
    weight: 80,
    type: "cover",
    finish: "vellum",
    variants: [
      {      
        id: "80c_french_dur-o-tone_aged_newsprint",
        name: "Aged Newsprint",
        longName: "80#c French Paper Co. Dur-O-Tone Aged Newsprint",
        rgb: "223, 208, 188",
        postLabel: "$$$",
      },
      {      
        id: "80c_french_dur-o-tone_newsprint_extra_white",
        name: "Newsprint Extra White",
        longName: "80#c French Paper Co. Dur-O-Tone Newsprint Extra White",
        rgb: "231, 230, 226",
        postLabel: "$$$",
      },
      {      
        id: "80c_french_dur-o-tone_newsprint_white",
        name: "Newsprint White",
        longName: "80#c French Paper Co. Dur-O-Tone Newsprint White",
        rgb: "229, 219, 205",
        postLabel: "$$$",
      },
      {      
        id: "80c_french_dur-o-tone_packing_brown_wrap",
        name: "Packing Brown Wrap",
        longName: "80#c French Paper Co. Dur-O-Tone Packing Brown Wrap",
        rgb: "190, 148, 84",
        postLabel: "$$$",
      },
    ]
  },
  {
    id: "70t_french_kraft-tone",
    name: "70#t French Paper Co. Kraft-Tone Vellum",
    brand: "French Paper Co.",
    line: "Kraft-Tone",
    weight: 70,
    type: "text",
    finish: "vellum",
    variants: [
      {      
        id: "70t_french_kraft-tone_brown_box",
        name: "Brown Box Kraft",
        longName: "70#t French Paper Co. Kraft-Tone Brown Box Kraft",
        rgb: "178, 128, 74",
        postLabel: "$$$",
      },
      {      
        id: "70t_french_kraft-tone_carbon_copy_box",
        name: "Carbon Copy Kraft",
        longName: "70#t French Paper Co. Kraft-Tone Carbon Copy Kraft",
        rgb: "132, 129, 117",
        postLabel: "$$$",
      },
      {      
        id: "70t_french_kraft-tone_chipboard_box",
        name: "Chipboard Kraft",
        longName: "70#t French Paper Co. Kraft-Tone Chipboard Kraft",
        rgb: "210, 205, 193",
        postLabel: "$$$",
      },
      {      
        id: "70t_french_kraft-tone_index_off-white",
        name: "Index Off-White Kraft",
        longName: "70#t French Paper Co. Kraft-Tone Index Off-White Kraft",
        rgb: "230, 226, 205",
        postLabel: "$$$",
      },
      {      
        id: "70t_french_kraft-tone_ledger_green",
        name: "Ledger Green Kraft",
        longName: "70#t French Paper Co. Kraft-Tone Ledger Green Kraft",
        rgb: "210, 221, 201",
        postLabel: "$$$",
      },
      {      
        id: "70t_french_kraft-tone_manila_yellow",
        name: "Manila Yellow Kraft",
        longName: "70#t French Paper Co. Kraft-Tone Manila Yellow Kraft",
        rgb: "236, 221, 184",
        postLabel: "$$$",
      },
      {      
        id: "70t_french_kraft-tone_memo_orange",
        name: "Memo Orange Kraft",
        longName: "70#t French Paper Co. Kraft-Tone Memo Orange Kraft",
        rgb: "239, 204, 182",
        postLabel: "$$$",
      },
      {      
        id: "70t_french_kraft-tone_packing_chip",
        name: "Packing Chip Kraft",
        longName: "70#t French Paper Co. Kraft-Tone Packing Chip Kraft",
        rgb: "205, 196, 197",
        postLabel: "$$$",
      },
      {      
        id: "70t_french_kraft-tone_paper_bag",
        name: "Paper Bag Kraft",
        longName: "70#t French Paper Co. Kraft-Tone Paper Bag Kraft",
        rgb: "207, 167, 103",
        postLabel: "$$$",
      },
      {      
        id: "70t_french_kraft-tone_parcel_wrap",
        name: "Parcel Wrap Kraft",
        longName: "70#t French Paper Co. Kraft-Tone Parcel Wrap Kraft",
        rgb: "229, 197, 148",
        postLabel: "$$$",
      },
      {      
        id: "70t_french_kraft-tone_standard_black",
        name: "Standard Black Kraft",
        longName: "70#t French Paper Co. Kraft-Tone Standard Black Kraft",
        rgb: "56, 56, 58",
        postLabel: "$$$",
      },
      {      
        id: "70t_french_kraft-tone_standard_white",
        name: "Standard White Kraft",
        longName: "70#t French Paper Co. Kraft-Tone Standard White Kraft",
        rgb: "233, 233, 233",
        postLabel: "$$$",
      },
    ]
  },
  {
    id: "other",
    name: "Other",
    brand: "",
    line: "",
    weight: 0,
    type: ['text','cover'],
    finish: "",
    variants: []
  }
 ]
